export const teamMembers = [
  {
    name: "Mr. Kinjal Puri",
    position: "Executive Chairman",
    qualification: "Semi-qualified CA, B.Com",
    image: "/images/kinjal.jpg",
    description: "Leading the firm with extensive experience in financial advisory and strategic planning.",
    fullDescription:
      "Mr. Kinjal Puri, the Executive Chairman of Wealthwise Consulting Pvt. Ltd., is a semi-qualified Chartered Accountant and holds a B.Com degree specializing in Accounting and Finance from a renowned institution in India. With over 7 years of professional experience, he brings deep expertise in auditing, accounting, taxation, and business consulting.\n\nMr. Puri has completed his articleship at one of India's top audit firms and has served as an Audit Manager at one of Nepal's oldest and most respected firms. His career includes extensive audit and advisory work for multinational corporations, public sector undertakings, listed entities, and private companies across both India and Nepal. His leadership reflects a commitment to precision, regulatory compliance, and delivering value-driven financial solutions to clients across borders.",
    experience: "7+ years",
    education: ["Semi-qualified Chartered Accountant", "B.Com (Accounting and Finance) from India"],
    email: "kinjal.wealthwise@outlook.com",
    phone: "+977-9843066123",
    linkedin: "linkedin.com/in/kinjalpuri",
    slug: "mr-kinjal-puri",
  },
  {
    name: "Mr. Bibek Parajuli",
    position: "Managing Director",
    qualification: "Semi-qualified CA, Bachelor's Degree",
    image: "/images/bibek.jpg",
    description: "Expert in taxation, compliance, and financial reporting with 5+ years of experience.",
    fullDescription:
      "Mr. Bibek Parajuli serves as the Managing Director of Wealthwise Consulting Pvt. Ltd. He is a semi-qualified Chartered Accountant and holds a Bachelor's degree from Tribhuvan University, Nepal. With over 5 years of experience in accounting, financial management, and business consulting, Mr. Parajuli brings strong analytical and strategic insight to the firm.\n\nHe completed his articleship at a reputed audit firm in India, gaining hands-on experience in various sectors. Since then, he has been instrumental in assisting clients with accounting solutions, financial planning, and investment decisions, helping them navigate complex financial landscapes with confidence. His expertise and client-centric approach play a vital role in driving operational excellence and trusted advisory services at Wealthwise.",
    experience: "5+ years",
    education: ["Semi-qualified Chartered Accountant", "Bachelor's Degree from Tribhuvan University, Nepal"],
    email: "bibek.wealthwise@outlook.com",
    phone: "+977-9741819815",
    linkedin: "linkedin.com/in/bibekparajuli",
    slug: "mr-bibek-parajuli",
  },
  {
    name: "Mr. Ramesh Shrestha",
    position: "Director",
    qualification: "Chartered Accountant (ICAI)",
    image: "/images/ramesh.jpg",
    description: "Specializes in business valuation, audit, and corporate finance solutions.",
    fullDescription:
      "Mr. Ramesh Shrestha is a Chartered Accountant, qualified from the Institute of Chartered Accountants of India (ICAI), and serves as a Consultant and Founding Shareholder at Wealthwise Consulting Pvt. Ltd. With over 5 years of experience in auditing, accounting, and business advisory, Mr. Shrestha brings a practical and entrepreneurial perspective to the firm.\n\nHe completed his articleship from a reputed Indian audit firm, where he developed a strong foundation in statutory audits, financial reporting, and compliance. Since qualifying, he has been actively involved in providing strategic business consulting services and is also engaged in managing and growing his own successful business ventures. His dual role as a professional advisor and entrepreneur adds valuable insight to the firm's client-focused solutions.",
    experience: "5+ years",
    education: ["Chartered Accountant from ICAI (India)", "Completed articleship from reputed Indian audit firm"],
    email: "ramesh.wealthwise@outlook.com",
    phone: "+977-9766954290",
    linkedin: "linkedin.com/in/rameshshrestha",
    slug: "mr-ramesh-shrestha",
  },
  {
    name: "Mr. Mausam Agrawal",
    position: "Director",
    qualification: "Chartered Accountant, Bachelor's Degree",
    image: "/images/mausam.jpg",
    description: "Oversees operations and client relationships with focus on business development.",
    fullDescription:
      "Mr. Mausam Agrawal is a qualified Chartered Accountant and holds a Bachelor's degree from Tribhuvan University (TU), Nepal. With over 8 years of overall experience and 4 years of post-qualification practice, he serves as a Consultant and Founding Shareholder at Wealthwise Consulting Pvt. Ltd.\n\nSince qualifying, Mr. Agrawal has been actively involved in professional practice and currently holds the position of Audit Manager at one of the top 10 Chartered Accountant firms in India. He possesses in-depth expertise in auditing, international taxation, and financial compliance, and has worked with a diverse portfolio of domestic and international clients. His strategic insight and technical proficiency make him a key contributor to the firm's high-quality advisory and assurance services.",
    experience: "8+ years",
    education: ["Chartered Accountant", "Bachelor's Degree from Tribhuvan University, Nepal"],
    email: "mausam.wealthwise@outlook.com",
    phone: "+91-9910567594",
    linkedin: "linkedin.com/in/mausamagrawal",
    slug: "mr-mausam-agrawal",
  },
  {
    name: "Mr. Bishal Dangol",
    position: "Senior Accountant",
    qualification: "Semi-qualified CA",
    image: "/images/bishal.jpg",
    description: "Handles complex accounting operations and financial analysis with precision.",
    fullDescription:
      "Mr. Bishal Dangol is a semi-qualified Chartered Accountant who has completed his articleship from a reputed CA firm in India. He currently serves as a Senior Accountant at Wealthwise Consulting Pvt. Ltd., where he plays a key role in delivering high-quality financial and consulting services.\n\nWith over 5 years of experience, Mr. Dangol has developed strong expertise in auditing, accounting, taxation, and business advisory. In addition to his role at Wealthwise, he actively provides independent business consultancy and investment decision support to a wide range of clients, including through online platforms. His analytical approach and commitment to client success make him a valuable asset to both the firm and the clients he serves.",
    experience: "5+ years",
    education: ["Semi-qualified Chartered Accountant", "Completed articleship from reputed CA firm in India"],
    email: "bishal.wealthwise@outlook.com",
    phone: "+977-9765411536",
    linkedin: "linkedin.com/in/bishaldangol",
    slug: "mr-bishal-dangol",
  },
  {
    name: "Mr. Nabraj Baral",
    position: "Finance Associate",
    qualification: "Master's & Bachelor's Degree",
    image: "/images/nabraj.jpg",
    description: "Supports financial operations and client service delivery with dedication.",
    fullDescription:
      "Mr. Nabraj Baral holds both a Bachelor's and a Master's degree from Tribhuvan University (TU), Nepal. With over 3 years of professional experience, he brings solid academic grounding and practical exposure to his role as a Finance Associate at Wealthwise Consulting Pvt. Ltd.\n\nMr. Baral began his career at a Chartered Accountancy firm, where he was involved in the audit of some of Nepal's leading companies. Following this, he served as a Finance Officer, further strengthening his expertise in accounting, financial reporting, and internal control systems. His combination of audit background and hands-on finance experience enables him to deliver precise and efficient financial support tailored to client needs.",
    experience: "3+ years",
    education: [
      "Master's Degree from Tribhuvan University, Nepal",
      "Bachelor's Degree from Tribhuvan University, Nepal",
    ],
    email: "nabraj.wealthwise@outlook.com",
    phone: "+977-9866473399",
    linkedin: "linkedin.com/in/nabrajbaral",
    slug: "mr-nabraj-baral",
  },
  {
    name: "Mr. Mohit Kharel",
    position: "Client Relationship Manager",
    qualification: "MBA Finance & Marketing, BBA",
    image: "/images/mohit.jpg",
    description: "Manages client relationships and ensures exceptional service delivery.",
    fullDescription:
      "Mr. Mohit Kharel holds an MBA in Finance and Marketing, along with a BBA, both earned from a reputable institution in Dehradun, India. He currently serves as the Client Relationship Manager at Wealthwise Consulting Pvt. Ltd., where he oversees client communication, service coordination, and relationship management with a focus on delivering seamless financial experiences.\n\nIn addition to his role at Wealthwise, Mr. Kharel is actively involved as a Client Account Manager for an Australian mortgage company. In this capacity, he works closely with brokers, solicitors, and lenders to facilitate end-to-end home loan processes, from loan structuring and document preparation to settlement coordination and post-settlement support. His deep understanding of the Australian mortgage landscape allows him to provide clients with clear guidance, tailored financial solutions, and timely updates throughout their loan journey.\n\nKnown for his exceptional interpersonal and communication skills, Mr. Kharel builds strong, trust-based relationships with clients and stakeholders alike. His professional background spans both accounting and marketing, with previous experience at a UK-based AACA firm and a private company. This diverse expertise positions him as a trusted advisor and invaluable point of contact for clients at Wealthwise.",
    experience: "5+ years",
    education: ["MBA in Finance and Marketing from Dehradun, India", "BBA from Dehradun, India"],
    email: "mohit.wealthwise@outlook.com",
    phone: "+977-9815338646",
    linkedin: "linkedin.com/in/mohitkharel",
    slug: "mr-mohit-kharel",
  },
]

export function getTeamMemberBySlug(slug: string) {
  return teamMembers.find((member) => member.slug === slug)
}
